name: Deploy Scorpion (Laravel on CentOS)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy to CentOS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}   # root
          key: ${{ secrets.SERVER_SSH_KEY }}     # tu id_rsa
          port: 22
          script: |
            echo "Entrando al proyecto..."
            cd /usr/share/nginx/html/genack

            echo "Actualizando repo..."
            git pull

            echo "Instalando dependencias de PHP..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "Ejecutando migraciones..."
            php artisan migrate --force

            echo "Limpiando y optimizando caché..."
            php artisan optimize:clear

            echo "Deploy completado."
